[theme]
primaryColor = "#E63946"  # A vibrant red accent
backgroundColor = "#F8F9FA"  # A soft neutral background
secondaryBackgroundColor = "#FFFFFF"  # Clean white for contrast
textColor = "#1D3557"  # Deep blue for better readability
font = "monospace"  # A sleek and modern font
